# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2eb24a1fb1ad545ce4ba84ac7397ecd4042e77c06baf67e422c295992aa446012e18f3b4fbad79be9cd9c4c40c7ebc772282545b11be8398dd8e56ba62bed2cd

test:
  secret_key_base: 1dbacb3269d5ceb1de49127c96fa66b952527a2755986b63db98c2850d93cbdc3b4d2248ceb643ccf0ab6c7cb485ced78e62dca134b73dffd60e0ca66041661e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
